### ISSUE TITLE
fix error

### ISSUE THREAD

**Issue by apuayush** [GDGVIT/gdginfo-backend#3]

**Comment by shubham0704** [comment]
I feel an issue must be opened when you want some discussion on it, maybe take a majority vote on some changes that you are going to perform.
Minor work for which you feel that there is no need for consent this one is pretty logical should be resolved then and there just mention your changes through a precise commit message.
You can also open an issue if you want to suggest some changes or improvements or point out some imperfections that need to be taken care of. If you feel this one is worth it open it when need be.

**Comment by apuayush** [comment]
sorry abt that but i did that test if score is getting updated .... really sorry
