### ISSUE TITLE
Decrease the weightage for opening issues

### ISSUE THREAD

**Issue by UjjwalAyyangar** [GDGVIT/gdginfo-backend#5]
Decrease the weight-age for opening issues while calculating a user's score as it is affecting the leaderboard.

**Comment by apuayush** [comment]
oky .. sure.

**Comment by apuayush** [comment]
done close if u feel like and ping me for anymore changes.

**Comment by UjjwalAyyangar** [comment]
@apuayush - Close this issue via commit message.
